owner: POCLANOS
repo: status

sites:
  - name: POCLANOS
    url: https://poclanos.com/

status-website:
  cname: status.poclanos.cord.town
  logoUrl: https://gallery.cord.town/media/original/poclanos/poclanos.jpg
  name: Status | POCLANOS
  introTitle: "**Upptime** for POCLANOS"
  introMessage: hello music junkies, we introduce the coolest K-Indie ever! enjoy your music life :)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://poclanos.cord.town/discord
